# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b6454a8c71dd8c8cdf072400e60f393b351aab4348d8d933c53ccc0dc9ee129c1629c19fc0b77fc72f2f10f133b42c613817aacd816340f0f1e7ef8fc053823

test:
  secret_key_base: 5b45ea1663775beafc26de07db78f3cad04a8ed9709c968d8812aeefbf4b2ce8239829c4fbdecc4f32618bc44e50e93117e2a6f97d2877a42622dc2a89341610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
